### ISSUE TITLE
Add features

### ISSUE THREAD

**Issue by pascaltuf** [JerwuQu/ggoled#3]
This project is great because unlike other apps on github it also hides that annoying USB-1 and that sonar icon, so as not to cause screen burn in.
In addition to the images, I would like to add the ability to have it show simple text or multiple sentences one below the other and in the center on the screen (if possible of course), I tried to modify the scripts to integrate them on windows for the clock and I tried to put more texts like the name of the song from spotify but creating an image every time with magick consumes resources and if the title of the song is too long the text cannot be seen in full, the only way is to create gifs to make the text scrolling, but it consumes resources.
Then with magick you cannot create the text under another text in a way to distinguish the artist with the song. (I didn't succeed)
So I ask in addition to the functions it can do, if you can add a function that gives it simple text and it writes it to you and if you have time put the scrolling if the sentence is too long so as to create scripts that show the time or the name of the song without needing to create images or gifs.

**Comment by JerwuQu** [comment]
Great ideas!

I'm not sure how inefficient imagemagick (or an alternative) is since it has to be converted to a bitmap anyways for sending over the USB protocol, but I have still considered it myself.

Do you have any ideas for how the CLI for it could look? I'm assuming you'd want to add text in multiple places and such.

**Comment by pascaltuf** [comment]
In my opinion the text could always remain in the center regardless and if there are multiple texts you put a separator that the program understands and puts the text at the end, like this:

Tiesto [space] Lay Low

The image shows an app that already does it gamesense-essential but there is that annoying usb1

![Example](https://github.com/user-attachments/assets/49c776c8-829c-4349-bb79-6168434db4ac)

**Comment by JerwuQu** [comment]
I added a basic `text` command. Please give it a try!

**Comment by JerwuQu** [comment]
Unrelated but I see you forked the repo for another model. Which exact model is it and do the commands seem to be working properly? If so I could merge it into this repo too.

**Comment by pascaltuf** [comment]
Thank you so much for your time to make this project better
My fork works for arctis nova pro wired.
It works as well as arctics nova pro wireless

**Comment by pascaltuf** [comment]
Now I'll test the program and tell you

**Comment by pascaltuf** [comment]
It works perfectly.
Now I'm waiting for what you put in TODO so that I have the centered text and other very useful things to perfect the program.
I didn't understand if you can already put the centered text via stdin as you wrote here:
Text, or omitted for stdin
What is stdin can you give me some info on how to use it?

**Comment by JerwuQu** [comment]
Awesome!

I will add alignment next :) 

stdin is only an alternate way to give the text and doesn't affect how it looks.
An example would be `echo Hello | ggoled text` which would give the same result as `ggoled text "Hello"` which is useful if you want to get input from another program.

**Comment by pascaltuf** [comment]
Ok, now I understand, thank you very much

**Comment by JerwuQu** [comment]
There! I have added more flexible positioning and text alignment.

See this example:
`ggoled text "Wow!" --clear --screen-x=center --screen-y=center --alignment=center`
Or the shorter version:
`ggoled text "Wow!" -C -x c -y c -a c`

The `-x`/`-y` take care of positioning, and the `-a` takes care of text alignment which is useful when the text is multiple lines.

**Comment by pascaltuf** [comment]
It works and thanks for adding my device.
Will you also put the possibility to add multiple lyrics one under the other?
Because I'm creating a small script in power shell that puts the song title + artist through your program and it would be nicer if I put the title above and the artist below for example

**Comment by JerwuQu** [comment]
For powershell you can use ``` `n ``` to signify a newline.

Example: ```ggoled text "Line1`nLine2`nLine3`nLine4" -C -y c```

**Comment by pascaltuf** [comment]
Wow I didn't know that, thanks it works now

**Comment by JerwuQu** [comment]
Glad it's working! :D 

Please open a new issue if you have additional requests such as text scrolling which are a lot more complicated.
