### ISSUE TITLE
Add gif support

### ISSUE THREAD

**Issue by Luporion** [JerwuQu/ggoled#5]
Having the option to add image sequences is great - being able to directly put gifs onto the screen would be even easier.

Is that possible?

**Comment by JerwuQu** [comment]
Hello! Yes, that's possible. Shouldn't be a lot of code either.

Would it make sense for it to animate at the same speed as the gif itself or do you need to be able to change it?

**Comment by Luporion** [comment]
I guess both features are useful, but most people would use the gifs stock speed and edit that if needed

**Comment by JerwuQu** [comment]
Hey! Please give the new build a try 😺

**Comment by Luporion** [comment]
Yes, works perfectly😊- thank you!
