### ISSUE TITLE
How to run the program?

### ISSUE THREAD

**Issue by carterl96** [JerwuQu/ggoled#6]
I'm not sure if I'm missing a prerequisite or what but I cant seem to run the actual program once installed?

**Comment by JerwuQu** [comment]
Hello!

I would need some more information (OS, product, usage, terminal) to help properly.

Have you used CLI applications before?

**Comment by carterl96** [comment]
> Hello!
> 
> 
> 
> I would need some more information (OS, product, usage, terminal) to help properly.
> 
> 
> 
> Have you used CLI applications before?

Hi there and thanks for the response! I don't think so? I ran the commands in both cmd and powershell with no luck :/

**Comment by carterl96** [comment]
> Hello!
> 
> I would need some more information (OS, product, usage, terminal) to help properly.
> 
> Have you used CLI applications before?

I got it working, was a directory issue on my end. Could this be used to run the official Steelseries gif's as well?

**Comment by carterl96** [comment]
> > Hello!
> > I would need some more information (OS, product, usage, terminal) to help properly.
> > Have you used CLI applications before?
> 
> I got it working, was a directory issue on my end. Could this be used to run the official Steelseries gif's as well?

Never mind ignore, just need to resize them to make them work.  I answered my own question. Nice work! It's a fun little thing to mess around with. This makes me want to try and implement the same thing to a lenovo clock I have at home
 https://www.lenovo.com/us/en/p/smart-devices/smart-home/smart-home-series/smart-clock-essential/zziszsdcd05?orgRef=https%253A%252F%252Fwww.google.com%252F

**Comment by JerwuQu** [comment]
Glad you got it working! 

Feel free to give updates if you make something fun :)
